const QUEUE_KEY='al-market-accounting-system-offline-queue-v1';
const DEVICE_KEY='al-market-accounting-system-device-v1';
const SYNC_KEY='al-market-accounting-system-sync-v1';
const URL_KEY='al-market-accounting-system-sync-url-v1';
const DEFAULT_SYNC_URL='http://localhost:8787';

export function getDeviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id='device_'+Date.now()+'_'+Math.random().toString(36).slice(2);localStorage.setItem(DEVICE_KEY,id)}return id}
export function readOfflineQueue(){try{const q=JSON.parse(localStorage.getItem(QUEUE_KEY)||'[]');return Array.isArray(q)?q:[]}catch{return[]}}
export function queueOperation(operation){if(!operation?.id||!operation?.type)return readOfflineQueue();const q=readOfflineQueue();if(q.some(x=>x.id===operation.id))return q;const next=[...q,{...operation,deviceId:getDeviceId(),queuedAt:operation.queuedAt||new Date().toISOString(),status:'pending'}];localStorage.setItem(QUEUE_KEY,JSON.stringify(next));return next}
export function markSynced(id){const next=readOfflineQueue().filter(x=>x.id!==id);localStorage.setItem(QUEUE_KEY,JSON.stringify(next));return next}
export function markConflict(id,reason,server){const next=readOfflineQueue().map(x=>x.id===id?{...x,status:'conflict',reason,server}:x);localStorage.setItem(QUEUE_KEY,JSON.stringify(next));return next}
export function retryConflict(id){const next=readOfflineQueue().map(x=>x.id===id?{...x,status:'pending',reason:undefined,server:undefined}:x);localStorage.setItem(QUEUE_KEY,JSON.stringify(next));return next}
export function clearOfflineQueue(){localStorage.removeItem(QUEUE_KEY)}
export function getConnectivity(){return typeof navigator==='undefined'?true:navigator.onLine}
export function queueIfOffline(operation){queueOperation(operation);return !getConnectivity()}
export function createSyncEnvelope(event){return{id:event.id,deviceId:getDeviceId(),createdAt:new Date().toISOString(),event}}
export function readSyncState(){try{return JSON.parse(localStorage.getItem(SYNC_KEY)||'{}')}catch{return{}}}
export function writeSyncState(patch){const next={...readSyncState(),...patch,updatedAt:new Date().toISOString()};localStorage.setItem(SYNC_KEY,JSON.stringify(next));return next}
export function getSyncUrl(){return localStorage.getItem(URL_KEY)||DEFAULT_SYNC_URL}
export function setSyncUrl(url){const clean=String(url||'').trim().replace(/\/$/,'');if(!/^https?:\/\//i.test(clean))throw new Error('عنوان خادم المزامنة غير صالح');localStorage.setItem(URL_KEY,clean);return clean}
export function getSyncStatus(){const q=readOfflineQueue();const s=readSyncState();return{online:getConnectivity(),pending:q.filter(x=>x.status==='pending').length,conflicts:q.filter(x=>x.status==='conflict').length,syncing:Boolean(s.syncing),lastSyncAt:s.lastSyncAt||null,lastError:s.lastError||null,deviceId:getDeviceId(),serverUrl:getSyncUrl()}}
export async function sendToSyncServer(envelope){const response=await fetch(getSyncUrl()+'/api/sync/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(envelope)});let data={};try{data=await response.json()}catch{}if(response.status===409||data.conflict)return{conflict:true,reason:data.reason||'تعارض يحتاج مراجعة',server:data.existing};if(!response.ok)throw new Error(data.error||('فشل الاتصال بخادم المزامنة: '+response.status));return data}
export async function checkSyncServer(){const response=await fetch(getSyncUrl()+'/health');if(!response.ok)throw new Error('خادم المزامنة غير متاح');return response.json()}
export async function processOfflineQueue({send=sendToSyncServer,onConflict}={}){if(!getConnectivity())return{processed:0,pending:readOfflineQueue().filter(x=>x.status==='pending').length,offline:true};const queue=readOfflineQueue();let processed=0,failed=0;writeSyncState({syncing:true,lastError:null});try{for(const operation of queue.filter(x=>x.status==='pending')){try{const result=await send(createSyncEnvelope(operation));if(result?.conflict){markConflict(operation.id,result.reason||'تعارض يحتاج مراجعة',result.server);if(onConflict)onConflict(operation,result);continue}markSynced(operation.id);processed++}catch(error){failed++;writeSyncState({lastError:error.message});break}}const pending=readOfflineQueue().filter(x=>x.status==='pending').length;writeSyncState({syncing:false,lastSyncAt:processed||!failed?new Date().toISOString():readSyncState().lastSyncAt||null});return{processed,pending,failed,offline:false}}catch(error){writeSyncState({syncing:false,lastError:error.message});throw error}}


export async function pullRemoteEvents({applyRemoteEvent}={}) { if(!getConnectivity()) return {pulled:0,offline:true}; const sync=readSyncState(); const after=Math.max(Number(sync.cursor||0),0); const response=await fetch(getSyncUrl()+'/api/sync/events?after='+after); let data={}; try{data=await response.json()}catch{} if(!response.ok) throw new Error(data.error||('فشل سحب عمليات المزامنة: '+response.status)); const events=Array.isArray(data.events)?data.events:[]; if(applyRemoteEvent) for(const record of events) await applyRemoteEvent(record.event,record); writeSyncState({cursor:Number(data.nextCursor??after+events.length),lastSyncAt:new Date().toISOString(),lastError:null}); return {pulled:events.length,cursor:Number(data.nextCursor??after+events.length),offline:false}; }
export async function syncAll({applyRemoteEvent}={}) { if(!getConnectivity()) return {processed:0,pulled:0,pending:readOfflineQueue().filter(x=>x.status==='pending').length,offline:true}; writeSyncState({syncing:true,lastError:null}); try{ const pushed=await processOfflineQueue(); const pulled=await pullRemoteEvents({applyRemoteEvent}); const pending=readOfflineQueue().filter(x=>x.status==='pending').length; writeSyncState({syncing:false,lastSyncAt:new Date().toISOString()}); return {processed:pushed.processed||0,pulled:pulled.pulled||0,pending,offline:false}; }catch(error){ writeSyncState({syncing:false,lastError:error.message}); throw error; } }
