import { useState } from 'react';
import { Plus, Search, Users, Truck, Wallet, UserRound, Camera, Settings, ShoppingCart } from 'lucide-react';
import { createId } from '../services/storage';

function TablePage({ title, description, icon: Icon, rows, columns, formFields, onAdd, addLabel }) {
  const [form, setForm] = useState(Object.fromEntries(formFields.map(f => [f.key, ''])));
  const [query, setQuery] = useState('');
  const filtered = rows.filter(row => Object.values(row).join(' ').toLowerCase().includes(query.toLowerCase()));
  const save = () => { if (!formFields.every(f => !f.required || String(form[f.key]).trim())) return; onAdd({ ...form, id: createId('row'), createdAt: new Date().toISOString() }); setForm(Object.fromEntries(formFields.map(f => [f.key, '']))); };
  return <section className="page-card"><div className="page-head"><div><h2>{title}</h2><p>{description}</p></div><Icon size={28}/></div><div className="toolbar"><div className="search-box"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث..."/></div></div><div className="form-grid compact">{formFields.map(f=><input key={f.key} type={f.type||'text'} placeholder={f.label} value={form[f.key]} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>)}<button className="primary-btn" onClick={save}><Plus size={18}/>{addLabel}</button></div><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{filtered.map(row=><tr key={row.id}>{columns.map(c=><td key={c.key}>{row[c.key] || '—'}</td>)}</tr>)}{!filtered.length&&<tr><td colSpan={columns.length} className="empty">لا توجد بيانات</td></tr>}</tbody></table></div></section>;
}

export function Customers({state,setState}) { return <TablePage title="العملاء" description="الحسابات والبيع الآجل والمدفوعات وكشوف الحساب" icon={Users} rows={state.customers} formFields={[{key:'name',label:'اسم العميل',required:true},{key:'phone',label:'رقم الهاتف'},{key:'openingBalance',label:'الرصيد الافتتاحي',type:'number'}]} columns={[{key:'name',label:'العميل'},{key:'phone',label:'الهاتف'},{key:'openingBalance',label:'الرصيد'}]} addLabel="إضافة عميل" onAdd={x=>setState({...state,customers:[...state.customers,x]})}/> }
export function Suppliers({state,setState}) { return <TablePage title="الموردون" description="المشتريات والديون والمدفوعات وكشوف الحساب" icon={Truck} rows={state.suppliers} formFields={[{key:'name',label:'اسم المورد',required:true},{key:'phone',label:'رقم الهاتف'},{key:'openingBalance',label:'الرصيد الافتتاحي',type:'number'}]} columns={[{key:'name',label:'المورد'},{key:'phone',label:'الهاتف'},{key:'openingBalance',label:'الرصيد'}]} addLabel="إضافة مورد" onAdd={x=>setState({...state,suppliers:[...state.suppliers,x]})}/> }
export function Employees({state,setState}) { return <TablePage title="الموظفون" description="ملفات الموظفين والرواتب والسلف والاستحقاقات" icon={UserRound} rows={state.employees} formFields={[{key:'name',label:'اسم الموظف',required:true},{key:'job',label:'الوظيفة'},{key:'salary',label:'الراتب',type:'number'}]} columns={[{key:'name',label:'الموظف'},{key:'job',label:'الوظيفة'},{key:'salary',label:'الراتب'}]} addLabel="إضافة موظف" onAdd={x=>setState({...state,employees:[...state.employees,x]})}/> }

export function Finance({state}) { const sales=state.sales.reduce((s,x)=>s+Number(x.total||0),0); const purchases=state.purchases.reduce((s,x)=>s+Number(x.total||0),0); return <section className="page-card"><div className="page-head"><div><h2>المالية</h2><p>الصناديق والمحافظ والتحويلات والمصروفات والإيرادات</p></div><Wallet size={28}/></div><div className="summary-row"><div><span>المبيعات</span><b>{sales.toLocaleString('ar-YE')} ر.ي</b></div><div><span>المشتريات</span><b>{purchases.toLocaleString('ar-YE')} ر.ي</b></div><div><span>صافي الحركة</span><b>{(sales-purchases).toLocaleString('ar-YE')} ر.ي</b></div></div><div className="module-grid">{['الصناديق الأربعة','المحافظ الإلكترونية','التحويلات','المصروفات','الإيرادات الأخرى','حركة الحسابات'].map(x=><div className="module-tile" key={x}><Wallet size={20}/><strong>{x}</strong><span>فتح وإدارة</span></div>)}</div></section> }

export function Purchases({state,setState}) { const [name,setName]=useState(''); const [total,setTotal]=useState(''); const save=()=>{if(!name.trim()||!Number(total))return;setState({...state,purchases:[...state.purchases,{id:createId('purchase'),supplier:name,total:Number(total),createdAt:new Date().toISOString()}]});setName('');setTotal('')}; return <section className="page-card"><div className="page-head"><div><h2>المشتريات</h2><p>فاتورة شراء نقدية أو آجلة أو جزئية مع ربط المورد والمخزون</p></div><ShoppingCart size={28}/></div><div className="form-grid compact"><input placeholder="المورد" value={name} onChange={e=>setName(e.target.value)}/><input type="number" placeholder="إجمالي الفاتورة" value={total} onChange={e=>setTotal(e.target.value)}/><button className="primary-btn" onClick={save}><Plus size={18}/> حفظ فاتورة شراء</button></div><div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>المورد</th><th>الإجمالي</th></tr></thead><tbody>{state.purchases.map(x=><tr key={x.id}><td>{new Date(x.createdAt).toLocaleString('ar-YE')}</td><td>{x.supplier}</td><td>{Number(x.total).toLocaleString('ar-YE')}</td></tr>)}</tbody></table></div></section> }

export function Cameras() { return <section className="page-card"><div className="page-head"><div><h2>الكاميرات والمراقبة</h2><p>المراقبة والتسجيل والأرشيف ضمن خيار مستقل داخل النظام</p></div><Camera size={28}/></div><div className="camera-grid">{['الكاميرا 1','الكاميرا 2','الكاميرا 3','الكاميرا 4'].map((x,i)=><div className="camera-card" key={x}><div className="camera-placeholder">{x}<small>{i===0?'متصلة':'غير متصلة'}</small></div><div><button className="secondary-btn">عرض مباشر</button><button className="secondary-btn">الأرشيف</button></div></div>)}</div></section> }

export function SettingsPage({state,setState}) { const [name,setName]=useState(state.settings.marketName); const save=()=>setState({...state,settings:{...state.settings,marketName:name}}); return <section className="page-card"><div className="page-head"><div><h2>الإعدادات</h2><p>إعدادات النظام الأساسية والهوية والعملة</p></div><Settings size={28}/></div><div className="settings-grid"><label>اسم النظام<input value={name} onChange={e=>setName(e.target.value)}/></label><label>العملة الأساسية<input value={state.settings.currency} readOnly/></label><div className="setting-note">الاسم المعتمد: نظام الماركت المحاسبي</div><button className="primary-btn" onClick={save}>حفظ الإعدادات</button></div></section> }
