import { useMemo, useState } from 'react';
import { BarChart3, FileText, Printer, Download, RefreshCw } from 'lucide-react';
import { getCurrentStock } from '../services/eventEngine';

const money=v=>Number(v||0).toLocaleString('ar-YE')+' ر.ي';
const dayStart=d=>{const x=new Date(d);x.setHours(0,0,0,0);return x};
export default function Reports({state}){
  const [from,setFrom]=useState(''),[to,setTo]=useState(''),[query,setQuery]=useState('');
  const inRange=(d)=>{const x=new Date(d);if(from&&x<dayStart(from))return false;if(to){const end=dayStart(to);end.setHours(23,59,59,999);if(x>end)return false}return true};
  const sales=useMemo(()=>state.sales.filter(x=>inRange(x.createdAt)),[state.sales,from,to]);
  const purchases=useMemo(()=>state.purchases.filter(x=>inRange(x.createdAt)),[state.purchases,from,to]);
  const totals={sales:sales.reduce((s,x)=>s+Number(x.total||0),0),purchases:purchases.reduce((s,x)=>s+Number(x.total||0),0),collected:sales.reduce((s,x)=>s+Number(x.paid||0),0),receivables:sales.reduce((s,x)=>s+Number(x.payments?.credit||0),0),inventory:state.items.reduce((s,x)=>s+getCurrentStock(state,x.id)*Number(x.cost||0),0)};
  const defs=[['sales','تقرير المبيعات'],['purchases','تقرير المشتريات'],['customers','كشف حساب العملاء'],['suppliers','كشف حساب الموردين'],['stock','حركة المخزون'],['finance','الحركة المالية'],['profit','تقرير الأرباح والتكاليف'],['audit','سجل العمليات والتدقيق']]; const reports=defs.filter(x=>x[1].includes(query.trim()));
  const exportCSV=(name,rows)=>{const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name+'.csv';a.click();URL.revokeObjectURL(a.href)};
  const exportReport=(key,name)=>{let rows=[];if(key==='sales')rows=[['التاريخ','الإجمالي','المدفوع','الآجل'],...sales.map(x=>[x.createdAt,x.total,x.paid,x.payments?.credit||0])];else if(key==='purchases')rows=[['التاريخ','المورد','الإجمالي','المدفوع','الآجل'],...purchases.map(x=>[x.createdAt,(state.suppliers.find(s=>s.id===x.supplierId)||{}).name,x.total,x.paid,x.payments?.credit||0])];else if(key==='customers')rows=[['العميل','الحركة','المبلغ'],...state.customerTransactions.filter(x=>inRange(x.occurredAt)).map(x=>[(state.customers.find(y=>y.id===x.customerId)||{}).name,x.type,x.amount])];else if(key==='suppliers')rows=[['المورد','الحركة','المبلغ'],...state.supplierTransactions.filter(x=>inRange(x.occurredAt)).map(x=>[(state.suppliers.find(y=>y.id===x.supplierId)||{}).name,x.type,x.amount])];else if(key==='stock')rows=[['التاريخ','الصنف','النوع','الكمية'],...state.stockMovements.filter(x=>inRange(x.occurredAt)).map(x=>[x.occurredAt,(state.items.find(y=>y.id===x.itemId)||{}).name,x.type,x.quantity])];else if(key==='finance')rows=[['التاريخ','النوع','طريقة الدفع','المبلغ','البيان'],...state.financeTransactions.filter(x=>inRange(x.occurredAt)).map(x=>[x.occurredAt,x.type,x.paymentMethod,x.amount,x.description])];else if(key==='audit')rows=[['التاريخ','النوع','المنفذ'],...(state.auditLog||[]).filter(x=>inRange(x.occurredAt)).map(x=>[x.occurredAt,x.type,x.actor])];else rows=[['البيان','القيمة'],['المبيعات',totals.sales],['المشتريات',totals.purchases],['صافي الحركة',totals.sales-totals.purchases]];exportCSV(name,rows)};
  return <section className="page-card"><div className="page-head"><div><h2>التقارير</h2><p>مركز التقارير الموحد للعمليات والأرصدة</p></div><BarChart3 size={28}/></div>
    <div className="report-toolbar"><label>من<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>إلى<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><div className="search-box"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث داخل التقارير..."/></div><button className="secondary-btn" onClick={()=>{setFrom('');setTo('');setQuery('')}}><RefreshCw size={16}/>إعادة</button></div>
    <div className="report-cards">{[['إجمالي المبيعات',totals.sales],['المشتريات',totals.purchases],['المحصّل',totals.collected],['الذمم الآجلة',totals.receivables],['قيمة المخزون',totals.inventory],['صافي الحركة',totals.sales-totals.purchases]].map(([name,value])=><div key={name}><span>{name}</span><b>{money(value)}</b></div>)}</div>
    <div className="report-list">{reports.map(([key,name])=><div className="report-row" key={key}><FileText size={19}/><span>{name}</span><div><button className="icon-btn" title="طباعة" onClick={()=>window.print()}><Printer size={16}/></button><button className="icon-btn" title="تصدير المبيعات CSV" onClick={()=>exportReport(key,name)}><Download size={16}/></button></div></div>)}</div>
  </section>
}
